name: Main CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Create spring.datasource.properties
        run: echo "${{ secrets.SPRING_DATASOURCE_PROPERTIES_PROD }}" > ./src/main/resources/spring.datasource.properties
      - name: Create cloud.aws.properties
        run: echo "${{ secrets.CLOUD_AWS_PROPERTIES_PROD }}" > ./src/main/resources/cloud.aws.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
